name: build

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        run: |
          export GO111MODULE=on
          GOOS=windows GOARCH=amd64 go build -o bin/ci-test-windows-amd64.exe ./src
          GOOS=linux   GOARCH=amd64 go build -o bin/ci-test-linux-amd64 ./src
      
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
