name: coverage

on: 
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: golang_example_db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calc coverage
        run: |
          go test ./... -coverprofile=coverage_unit.out
          go test ./tests -coverpkg=./... -coverprofile=coverage_int.out
          grep 'mode' coverage_unit.out > coverage.out.tmp
          grep 'github' coverage_unit.out >> coverage.out.tmp
          grep 'github' coverage_int.out >> coverage.out.tmp
          grep -A10 'files:' ignore_test.yml | grep -v "files:" | sed 's/ //g' > coverage.out.list
          grep -v -F -f coverage.out.list coverage.out.tmp > coverage.txt

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: true
